version: '3'
services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code/CozyCave-back
    command: bash -c "pwd && uvicorn app.main:app --reload --host 0.0.0.0"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      
      
      